######################################################################
# Automatically generated by qmake (2.01a) czw. pa? 21 05:30:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DEFINES += VIEWER

# Input
HEADERS += include/mainwindow.h include/scriptwindow.h
SOURCES += src/app/mainwindow.cpp src/app/main.cpp src/script/scriptwindow.cpp

FORMS    += src/script/scriptwindow.ui
